name: serinus_liquify
description: Integration of the Liquify template engine with Serinus.
version: 1.0.2
repository: https://github.com/avesbox/serinus_liquify
homepage: https://serinus.app/plugins/serinus_liquify.html
topics:
  - serinus
  - liquify
  - template
  - engine
  - integration

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  liquify: ^1.2.0
  serinus: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
